DUBO_PROJECT_NAME = DuboMegaUp
DUBO_VENDOR_NAME = DuboDubonDuponey
DUBO_PROJECT_VERSION_MAJOR = 1
DUBO_PROJECT_VERSION_MINOR = 0
DUBO_PROJECT_VERSION_PATCH = 0
DUBO_MINIMUM_QT = 4.6
DUBO_MIN_OSX = 10.7
