DUBO_PROJECT_NAME = DuboUp
DUBO_VENDOR_NAME = DuboDubonDuponey
DUBO_PROJECT_VERSION_MAJOR = 2
DUBO_PROJECT_VERSION_MINOR = 0
DUBO_PROJECT_VERSION_PATCH = 0
DUBO_MINIMUM_QT = 5.6
DUBO_MIN_OSX = 10.10
DUBO_LINK_TYPE = dynamic
